language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
install:
  - travis_retry pip install tox-travis
script:
  - tox
after_success:
  - "if [ $TRAVIS_PYTHON_VERSION == '2.7' ]; then pip install coveralls; coveralls; fi"
