language: python
python:
  - "3.5"
sudo: false
install:
  # virtualenv>=14.0.0 has dropped Python 3.2 support
  - travis_retry pip install "virtualenv<14.0.0"
  - travis_retry pip install tox
script:
  - tox
after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"
