name: Features

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    permissions:
      contents: read       # checkout
      deployments: write   # ably/sdk-upload-action
      id-token: write      # aws-actions/configure-aws-credentials (OIDC)
    uses: ably/features/.github/workflows/sdk-features.yml@main
    with:
      repository-name: ably-python
    secrets: inherit
