name: Features

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: ably/features/.github/workflows/sdk-features.yml@main
    with:
      repository-name: ably-python
    secrets: inherit
